title: DS4 SRD+
description: Regelreferenz und Fanwerke für <a href="https://www.dungeonslayers.net/">Dungeonslayers 4.0</a> © Christian Kennig<br/><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>