#!/bin/sh

./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/adler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/alligator.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/ankmatur.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/augenball.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/baer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/basilisk.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/baumherr.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/daemonenfuerst.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/drachenwelpe.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/echsenmensch.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/einhorn.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/emrich.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/erdelementar-iii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/erdelementar-ii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/erdelementar-i.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/erwachsener-drache.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/eulerich.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/faulbauchmade.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/faulbauch.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/feuerelementar-iii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/feuerelementar-ii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/feuerelementar-i.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/fliegendes-schwert.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/gargyl.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/geist.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/goblin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/golem-eisen-.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/golem-knochen-.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/golem-kristall-.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/golem-lehm-.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/golem-stein-.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/hai.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/harpyie.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/harringer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/hobgoblin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/hoher-daemon.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/hund.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/hydra.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/jungdrache.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/kampfdaemon.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/kamp.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/keiler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/kleine-monsterspinne.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/kobold.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/kriegsdaemon.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/kriegselefant.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/lebende-ruestung.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/leichnam.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/luftelementar-iii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/luftelementar-ii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/luftelementar-i.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/medusa.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/minotaurus.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/monsterspinne.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/mumie.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/niederer-daemon.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/oger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/ork.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/orkraeuber.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/pferd.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/pony.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/ratte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/raubkatze.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/reitkeiler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/riese.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/riesenechse.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/riesenkrake.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/riesenratte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/riesenschlange.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/ritter-wilbert.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/rostassel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/schatten.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/schimmerross.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/schlachtross.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/schlingwurzelbusch.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/shekz.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/skelett.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/tentakelhirn.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/todesfee.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/troll.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/unwolf.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/vampirfledermaus.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/wasserelementar-iii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/wasserelementar-ii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/wasserelementar-i.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/wegelagerer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/wolf.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tmp.txt ./grw/bestiarium/zombie.md