#!/bin/sh

./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/aensteiner-soldat.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/aensteiner-wilderer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/airigh.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/akyna.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/al-nuzzran.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/anarioth-der-sturmrufer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/angischer-clanskrieger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/apokalpytischer-reiter-der-pestilenz.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/apokalpytischer-reiter-des-hungers.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/apokalpytischer-reiter-des-kriegs.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/apokalpytischer-reiter-des-todes.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/apokalpytisches-ross.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/arbeiter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/arcuna.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/arken-beijl.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ascheelf-krieger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ascheelf-raecher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ascheelf-spaeher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/asphyx.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/baby-monsterspinne.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/barex.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/baumgolem.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/belgor.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/bergzwergischer-soeldner.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/berna-priesterin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/bestiarium-fanwerk.sh
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/billiger-soeldner.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/blasaminator.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/blob.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/bosker-sturmkraehe-soeldner.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/brambel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/brasko.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/brutac.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/bulegor.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/caerner-freibeuter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/casius.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/chalog-omesch.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/chien-kwan.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/chio-puan-wandermoench.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/copperntaler-milizionaer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/cranag-der-wanderer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/dampfkutsche.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/deformierter-drachenwelpe.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/der-ketzer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/dermot-madal.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/der-weltenfresser.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/die-eiskoenigin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/dirion.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/donnerechse.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/donnervogel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/drac.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/drazuul-die-verderberin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/duldgnomischer-zaubertechniker.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/dunkler-krieger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/einbrecher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/eiselementar-iii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/eisenhaller-armbrustschuetze.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/eiswolf.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/eiszwerg.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/eldvyn.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/engel-der-apokalypse.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/enural.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/erald.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/erfahrener-rattling.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/erindor.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ettin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/fahlstepper-grenzwaechter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/falschspieler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/faria-feuermagierin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/fenya.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/fetter-goblin-aufseher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/fjordinger-wikinger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/fjordorzwergischer-kaperfahrer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/fliegender-schaedel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/floragon.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/freilaender-daemonenjaeger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/funkenfieper.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gaertner.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/galen.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/geistpeiniger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/getreuer-dammenhalls.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gisamor.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/glitzerhand-dieb.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gloriel-die-kraeuterhexe.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gnomischer-illusionist.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-berserker.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-bomber.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-giftmoerder.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-haeuptling.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-krieger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblinraecher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-schamane.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-spaeher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/goblin-stadtratte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gralbor-weissauge.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/grossmutter-gorla.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/grottenschrat.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/grufthauptmann.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gruftpluenderer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/gruftritter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/halblingskelett.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/hartmund.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/heiler-schuetze-01.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/heiler-schuetze-04.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/heiler-schuetze-08.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/heiler-schuetze-12.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/heimsucher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/hellweiter-diplomat.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/heob-ordensheiler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/hilaner-priester.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/hilanischer-peltast.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/iglorion.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/irrlicht.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/joedlaender-schamanin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/jok-von-walderson.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/josip.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/jost-rotweiden.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kaholwaechter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kait-jadedrache.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kait-ninja.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kait-schwertgelehrter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kampfmagier-01.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kampfmagier-04.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kampfmagier-08.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kampfmagier-12.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kavija-die-uralte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kerberos.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kleine-mordmuecke.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kleiner-augenball.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kleiner-borstenwurm.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kleiner-knochengolem.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/komplize.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kral-der-schreckliche.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kroetenhaut.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kruga.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/kultist-in-mautmoreen.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/lebende-wurzel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/lehrling-in-aenkmator.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/lios.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/lord-dammenhall.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/lufrelementardiener.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/luftdaemon-iii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/luftdaemon-ii.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/luftdaemon-i.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/luftelementarbote.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/lydenia.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/mammut.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/mardossani-kavalier.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/maskentaenzerin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/mega-skelett.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/meister-schnarkel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/menschensklave.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/minderer-leichnam.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/mokaner-faehrtenleser.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/morg-bulgash.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/mudaks-die-gruenhaut.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/mutierte-riesenratte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/nafuri-soeldner.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/nancor-der-baerenwueter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/narrlaender-alchemist.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/nekrolyth.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/nico-mavelli.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/nordeker-ritter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/pfeilsporenpilz.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/phantomhexer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/raeuber.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattenkoenig.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattenkoenig-schnabbler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattenoger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattling-giftzauberer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattling-kriegshaeuptling.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattling.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rattling-seuchenpriester.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rekrut-der-reiter-der-morgenroete.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/remnaton.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/riesenaffe.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/riesenpterodactylus.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/riesensumpfotter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ritter-01.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ritter-04.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ritter-08.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ritter-12.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ritter-gungart.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/rogg-umbar-barbar.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ryan-dougal.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/saebelzahntiger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sanuriel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schattenkultist.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schattenpriester.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schattenwolf.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schlaechter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schnappaal.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schneeriese.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/schreckensdachs.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sensenmann.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sinda.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/skelettdrache.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/skelettkrieger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/skelettmagier.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/skelettschuetze.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/stadtwache-in-den-freien-landen.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sternheider-forscher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/stig.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/stolpervogel.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sturmmeerkatze.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sturmsegler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/sumpfechse.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/tarc-trepios.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/tarr-novize.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/tigerskelett.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/tintenkraken.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/tonkriegergolem.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/umbar-barbar.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/umbarlageier.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untote-mannshand.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untoter-goblin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untoter-oger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untoter-ork.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untoter-priester.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untoter-waechter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/untote-werratte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/vandrianischer-minnesaenger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/vandrianischer-ordensheiler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/vandrianischer-ordensritter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/vandrianischer-waffenknecht.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/varissa.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/verzauberter-besen.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/vestracher-einbrecher.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/virgil.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/vladek-crumm.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/walkuere-von-wyndstett.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/werkzeug.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/wilder-rattling.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/wilfried-von-eibenhoeh.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/wolfbart.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/wollnashorn.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/wyndlaendischer-schwarzmagier.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/ynnari-schwester-des-waldes.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zasarischer-feuermagier.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zasarischer-kauffahrer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zasarischer-maerchenerzaehler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombiebaer.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombiedrache.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombiegoblin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombiekeiler.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombieoger.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombieork.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombieriesenratte.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombie-sekretaerin.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombietroll.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zombiewolf.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zwergensklave.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/zwergischer-minenarbeiter.md
./_assembly/scripts/tokens/replace-tokens.pl _assembly/scripts/tokens/tokens-for-bestiarium.txt ./fanwerk/bestiarium/