name: Transform MD into HTML
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make HTML pages
        run: |
          pandoc
          --standalone
          --output=index.html
          index.md
      - name: Commit repository
        with:
          ref: ${{ github.head_ref }}
        run: |
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated HTML pages."
          git push
